### ISSUE TITLE
ConDA on different LiDAR sensors

### ISSUE THREAD

**Issue by dream-toy** [ldkong1205/ConDA#1]
Hi, thanks for your great work.

After reading this paper, I wondered how CONDA performed on the data scanned by different LiDARs. For example, the source domain is semanticKITTI (64-beam LiDAR), and the target domain is nuScenes (32-beam LiDAR). In this case, the RV images are different sizes and will affect Domain Concatenation. How to tackle this problem?

**Comment by ldkong1205** [comment]
Hi @dream-toy, thank you for your interest in this work!

For your question: It is hard to extend the kind of strategy to the cross-sensor scenario since the different sensor setups bring extra domain gaps. This is also the reason why we are targeting cross-city UDA (with the same LiDAR setup) in this work. We argue that the cross-sensor scenario is much less common than the cross-city scenario, since the same company tends to use unified hardware.

Although we haven't officially tried UDA between two datasets with different beams, the concatenation of them is actually applicable. Recall that the slicing RV images along the vertical axis is equivalent to splitting point clouds based on the point inclination angles. Therefore, you can tackle this problem by mixing domains at the point-level, rather than at the RV images. Nonetheless, more considerations are indeed needed to successfully implement this; for example, you will need to first align the FOVs of these two datasets, especially on the z-axis; and also unify the label mappings.

Hope the above answers your question. Please feel free to contact us if you have any other questions.

**Comment by dream-toy** [comment]
Thank you for your quick reply. It helps me a lot.

**Comment by ldkong1205** [comment]
> Thank you for your quick reply. It helps me a lot.

Hi @dream-toy, we are glad to hear that we are helping! For mixing raw points, please refer to more details in [this](https://arxiv.org/abs/2207.00026) paper. We will release the code soon.

Please re-open the issue if you have any other questions!
